# prometheus.yml
global:
    scrape_interval: 5s
scrape_configs:
    - job_name: 'exporter'
      metrics_path: '/metrics'
      static_configs:
          - targets: ['exporter:8070']
          - targets: ['push-gateway:9091']
   
    
