# prometheus.yml
global:
    scrape_interval: 5s
scrape_configs:
    - job_name: 'graphite-writer'
      metrics_path: '/actuator/prometheus'
      static_configs:
          - targets: ['graphite-writer:8084']
    - job_name: 'influxdb-writer'
      metrics_path: '/actuator/prometheus'
      static_configs:
          - targets: ['influxdb-writer:8083']
   
    
